### ISSUE TITLE
Graph goes out of screen when rerunning layout 

### ISSUE THREAD

**Issue by SelbiEreshova** [SelbiEreshova/willow#1]

**Comment by ugurdogrusoz** [comment]
@SelbiEreshova Looks like you fixed this by fitting the graph in window each time. This is a work around. A better solution is to find out whey the graph is shifting. An incremental layout should not shift a graph so drastically. There is something weird going on here.

**Comment by SelbiEreshova** [comment]
The issue is in GraphDrawer.js in ` function updateCytoscape()`. Previous developers were initializing the pan and zoom of the updated graph as the same as the previous graph.
