### ISSUE TITLE
Willow will not display in some web pages

### ISSUE THREAD

**Issue by ugurdogrusoz** [SelbiEreshova/willow#7]
Willow window will not display in certain web pages such as web.skype.com and drive.google.com (when signed in). Any particular reason this is not so?

**Comment by SelbiEreshova** [comment]
The reason for this issue could be that the side panel _only_ shows for those sites that were loaded after Willow was loaded(activated). If the cites that you mentioned were loaded before Willow then this could be the reason why the side panel is not showing.
